In [ ]:
#To decide which one model is perfect for the dataset
#to check the models performance
#we divide the dataset into fold
#example like 100 samples in a datset
# we divide the dataset into 20 folds and in first iteration i train the 4 fold and first one for test and in second iteration i test the second fold and remaining for training and do so and average score is taken

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
digits = load_digits()
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)


In [ ]:
lr=LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9555555555555556

In [ ]:
svm=SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.987037037037037

In [ ]:
rf=RandomForestClassifier()
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9666666666666667

In [ ]:
#when we re-execute the X_train and x_test and the sample we are putting into model changes so the accuracy also changes
#so train test split will not always give accurate performance so we use k fold
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf
#spliting the datasets into k fold

KFold(n_splits=3, random_state=None, shuffle=False)

In [ ]:
for train_index ,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
      print(train_index,test_index)
# it divide the datset into 3 fold because earlier we have mentioned it to divide it to divide it into 3 folds and the data we have given here i 1 to 9


[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [ ]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)


In [ ]:
get_score(LogisticRegression(),X_train,X_test,y_train,y_test)
#This function trains a machine learning model on training data and evaluates its accuracy on test data.

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9555555555555556

In [ ]:
get_score(SVC(),X_train,X_test,y_train,y_test)

0.987037037037037

In [ ]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)
#StratifiedKFold is a way to split data into training and testing sets while making sure that the proportion of each class (category) remains the same in every split.


In [ ]:
#Three empty lists are created to store model scores:
score_l=[]
score_svm=[]
score_rf=[]
for train_index,test_index in kf.split(digits.data):
    X_train,X_test,y_train,y_test=digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    get_score(LogisticRegression(),X_train,X_test,y_train,y_test)
    get_score(SVC(),X_train,X_test,y_train,y_test)
    get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test)

print("Logistic Regression Scores:", score_l)
print("SVM Scores:", score_svm)
print("Random Forest Scores:", score_rf)


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

Logistic Regression Scores: []
SVM Scores: []
Random Forest Scores: []


In [ ]:
#instead of doing the above code we can do like this also
from sklearn.model_selection import cross_val_score

In [ ]:
cross_val_score(LogisticRegression(),digits.data,digits.target)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [ ]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [ ]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target)
#n_estimators=40 increasing the no of trees and this is called parameter tuning

array([0.93333333, 0.88055556, 0.94707521, 0.94428969, 0.91086351])